import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

const sidebarsLeap: SidebarsConfig = {
  leap: [
    {
      type: 'doc',
      id: 'index',
      label: 'Introduction',
    },
    {
      type: 'category',
      label: 'Edge SDK',
      items: [
        'edge-sdk/overview',
        {
          type: 'category',
          label: 'Android',
          items: [
            {
              type: 'autogenerated',
              dirName: 'edge-sdk/android',
            },
          ],
        },
        {
          type: 'category',
          label: 'iOS',
          items: [
            {
              type: 'autogenerated',
              dirName: 'edge-sdk/ios',
            },
          ],
        },
      ],
    },
    {
      type: 'doc',
      id: 'finetuning',
      label: 'Finetuning',
    },
    {
      type: 'category',
      label: 'Model Bundling Service',
      items: [
        {
          type: 'autogenerated',
          dirName: 'leap-bundle',
        },
      ],
    },
    {
      type: 'doc',
      id: 'laptop-support',
      label: 'Laptop Support',
    },
    {
      type: 'doc',
      id: 'changelog',
      label: 'Changelog',
    },
  ],
};

export default sidebarsLeap;
