import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

const sidebarsLeap: SidebarsConfig = {
  leap: [
    {
      type: 'doc',
      id: 'index',
      label: 'Introduction',
    },
    {
      type: 'doc',
      id: 'find-model',
      label: 'Best model search',
    },
    {
      type: 'doc',
      id: 'vibe-check-models',
      label: 'Vibe-check models',
    },
    {
      type: 'category',
      label: 'Deploy to mobile device',
      items: [
        'edge-sdk/overview',
        {
          type: 'category',
          label: 'Android',
          items: [
            {
              type: 'autogenerated',
              dirName: 'edge-sdk/android',
            },
          ],
        },
        {
          type: 'category',
          label: 'iOS',
          items: [
            {
              type: 'autogenerated',
              dirName: 'edge-sdk/ios',
            },
          ],
        },
      ],
    },
    {
      type: 'doc',
      id: 'laptop-support',
      label: 'Deploy to laptop',
    },
    {
      type: 'category',
      label: 'Customize model',
      items: [
        'finetuning',
        {
          type: 'category',
          label: 'Model Bundling Service',
          items: [
            {
              type: 'autogenerated',
              dirName: 'leap-bundle',
            },
          ],
        },
      ],
    },
    {
      type: 'doc',
      id: 'changelog',
      label: 'Changelog',
    },
    {
      type: 'link',
      label: 'Discord',
      href: 'https://discord.gg/DFU3WQeaYD',
    },
  ],
};

export default sidebarsLeap;
